-- Messaging System
CREATE TABLE public.messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  sender_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  receiver_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  content TEXT NOT NULL,
  is_read BOOLEAN DEFAULT FALSE
);

ALTER TABLE public.messages ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own messages." ON public.messages
  FOR SELECT USING (auth.uid() = sender_id OR auth.uid() = receiver_id);

CREATE POLICY "Users can send messages." ON public.messages
  FOR INSERT WITH CHECK (auth.uid() = sender_id);

-- Rating & Review System
CREATE TABLE public.reviews (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  reviewer_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  reviewee_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  contract_id BIGINT REFERENCES public.contracts(id) ON DELETE SET NULL,
  rating INTEGER CHECK (rating >= 1 AND rating <= 5),
  comment TEXT,
  UNIQUE(reviewer_id, reviewee_id, contract_id)
);

ALTER TABLE public.reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Reviews are viewable by everyone." ON public.reviews
  FOR SELECT USING (true);

CREATE POLICY "Users can create reviews for their contracts." ON public.reviews
  FOR INSERT WITH CHECK (auth.uid() = reviewer_id);

-- Payment Integration (M-Pesa focus)
CREATE TABLE public.payments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  contract_id BIGINT NOT NULL REFERENCES public.contracts(id) ON DELETE CASCADE,
  amount NUMERIC NOT NULL,
  status TEXT DEFAULT 'pending', -- 'pending', 'completed', 'failed'
  transaction_id TEXT UNIQUE,
  payment_method TEXT DEFAULT 'mpesa'
);

ALTER TABLE public.payments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Users can view their own payments." ON public.payments
  FOR SELECT USING (
    auth.uid() IN (
      SELECT employer_id FROM public.contracts WHERE id = contract_id
      UNION
      SELECT worker_id FROM public.contracts WHERE id = contract_id
    )
  );

-- Verification Flow
CREATE TABLE public.verification_requests (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  worker_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
  id_document_url TEXT,
  police_clearance_url TEXT,
  notes TEXT
);

ALTER TABLE public.verification_requests ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Workers can view and create their own verification requests." ON public.verification_requests
  FOR ALL USING (auth.uid() = worker_id);
