-- Training System Tables
CREATE TABLE public.courses (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  title TEXT NOT NULL,
  description TEXT NOT NULL,
  category TEXT NOT NULL, -- e.g., 'Childcare', 'Culinary', 'Housekeeping'
  duration TEXT, -- e.g., '2 hours', '3 days'
  thumbnail_url TEXT,
  content_url TEXT, -- Link to video or PDF
  modules JSONB DEFAULT '[]'::jsonb,
  quiz_data JSONB DEFAULT '{"questions": []}'::jsonb
);

CREATE TABLE public.enrollments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
  worker_id UUID NOT NULL REFERENCES public.profiles(id) ON DELETE CASCADE,
  course_id BIGINT NOT NULL REFERENCES public.courses(id) ON DELETE CASCADE,
  status TEXT DEFAULT 'enrolled', -- 'enrolled', 'in-progress', 'completed'
  progress INTEGER DEFAULT 0,
  completed_at TIMESTAMP WITH TIME ZONE,
  UNIQUE(worker_id, course_id)
);

ALTER TABLE public.courses ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Everyone can view courses." ON public.courses FOR SELECT USING (true);

ALTER TABLE public.enrollments ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Workers can manage their own enrollments." ON public.enrollments FOR ALL USING (auth.uid() = worker_id);

-- Seed some initial courses with Kenyan-tailored images and titles
INSERT INTO public.courses (title, description, category, duration, thumbnail_url) VALUES 
('Elite Nanny Certification', 'Mastering Kenyan childcare standards, child safety, and modern developmental play.', 'Childcare', '4 hours', 'https://images.unsplash.com/photo-1531123897727-8f129e1688ce?q=80&w=1974'),
('Continental & Kenyan Cuisine', 'Professional culinary techniques for preparing local favorites and international dishes.', 'Culinary', '6 hours', 'https://images.unsplash.com/photo-1621360841013-c7683c659ec6?q=80&w=2076'),
('Executive Home Management', 'Advanced organization and professional cleaning standards for high-end Kenyan households.', 'Housekeeping', '3 hours', 'https://images.unsplash.com/photo-1523213139764-415255973bc5?q=80&w=1924');
